# Generated by Django 5.1.2 on 2024-10-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
