# Generated by Django 5.1.2 on 2024-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_user', '0004_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
