# Generated by Django 5.1.2 on 2024-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_user', '0006_alter_patient_first_name_alter_patient_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
