# Generated by Django 5.1.2 on 2024-10-16 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accountant_image', models.ImageField(blank=True, null=True, upload_to='accountants')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_handled', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_image', models.ImageField(blank=True, null=True, upload_to='hr')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('nurse_image', models.ImageField(blank=True, null=True, upload_to='nurses')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist_image', models.ImageField(blank=True, null=True, upload_to='receptionists')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
    ]
