# Generated by Django 5.1.2 on 2024-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.ImageField(blank=True, null=True, upload_to='departmentss'),
        ),
    ]
