# Generated by Django 5.1.2 on 2024-10-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0005_remove_doctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='shift',
        ),
    ]
