# Generated by Django 5.1.2 on 2024-10-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0008_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receptionist_image', models.ImageField(blank=True, null=True, upload_to='accountants')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosp_staff.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Accountant',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
