# Generated by Django 5.1.2 on 2024-10-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0010_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='salary',
        ),
    ]
