# Generated by Django 5.1.2 on 2024-11-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0012_companylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='receptionist_image',
            field=models.ImageField(blank=True, null=True, upload_to='receptionist'),
        ),
    ]
