# Generated by Django 5.1.2 on 2024-11-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0013_alter_receptionist_receptionist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
