# Generated by Django 5.0.6 on 2024-11-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0018_alter_availability_unique_together_and_more'),
    ]

    operations = [
    ]
