# Generated by Django 5.0.6 on 2024-11-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0019_auto_20241106_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='available_date',
        ),
    ]
