# Generated by Django 5.0.6 on 2024-11-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0021_auto_20241106_1033'),
    ]

    operations = [
    ]
