# Generated by Django 5.0.6 on 2024-11-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_staff', '0022_auto_20241106_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(max_length=9),
        ),
    ]
